# スクリーンショットが保存されるディレクトリ($HOME/{captureDir})
captureDir: Pictures
# スクリーンショットのファイル名のフォーマット(詳しくは https://golang.org/pkg/path/filepath/#Match)
captureFilePattern: "Screenshot from [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]-[0-9][0-9]-[0-9][0-9]"
# スクリーンショットの拡張子
extension: .png
# 移動後にファイル名を連番にする場合の桁数
sequestialDigits: 3
